#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
#            - mvn -B verify --file pom.xml
            - echo "$(ls -la)"
            - ls
            - pwd
            - mvn compile
            - mvn package
            - java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App
            - echo "$(ls -la src/)"
#    - scp -r ./* --exclude "bitbucket-pipelines.yml" user@34.132.124.169:/home/user/new
